/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import org.kohsuke.randname.*;


fun main() {
    val rnd = RandomNameGenerator(0);
    for (i in 1..3) {
        println(rnd.next());
    }
}
